//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoGiaoDich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoGiaoDich()
        {
            this.KhoGiaoDich1 = new HashSet<KhoGiaoDich>();
            this.KhoGiaoDichChiTiets = new HashSet<KhoGiaoDichChiTiet>();
        }
    
        public System.Guid Id { get; set; }
        public string MaGiaoDich { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.Guid IdNguoiTao { get; set; }
        public string LoaiGiaoDich { get; set; }
        public bool DaXoa { get; set; }
        public Nullable<System.Guid> IdKhoaPhong { get; set; }
        public string GhiChu { get; set; }
        public string NguoiGiaoNhan { get; set; }
        public Nullable<System.Guid> IdKho { get; set; }
        public Nullable<System.Guid> IdGiaoDichCha { get; set; }
        public Nullable<System.Guid> idNhaCungCap { get; set; }
        public string SoHopDong { get; set; }
        public Nullable<System.DateTime> NgayHopDong { get; set; }
    
        public virtual Kho Kho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoGiaoDich> KhoGiaoDich1 { get; set; }
        public virtual KhoGiaoDich KhoGiaoDich2 { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TuDien TuDien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoGiaoDichChiTiet> KhoGiaoDichChiTiets { get; set; }
    }
}
