//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoSanPham()
        {
            this.KhoGiaoDichChiTiets = new HashSet<KhoGiaoDichChiTiet>();
            this.KhoTons = new HashSet<KhoTon>();
        }
    
        public System.Guid Id { get; set; }
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string GhiChu { get; set; }
        public System.Guid IdDonViTinh { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<System.Guid> IdNhomVatTu { get; set; }
        public string XuatXu { get; set; }
        public string KyhieuNhanmac { get; set; }
        public string ThoiGianBaoHanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoGiaoDichChiTiet> KhoGiaoDichChiTiets { get; set; }
        public virtual NhomVatTu NhomVatTu { get; set; }
        public virtual TuDien TuDien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoTon> KhoTons { get; set; }
    }
}
