//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyKhoEntities : DbContext
    {
        public QuanLyKhoEntities()
            : base("name=QuanLyKhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<KhoGiaoDichChiTiet> KhoGiaoDichChiTiets { get; set; }
        public virtual DbSet<KhoTon> KhoTons { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TuDien> TuDiens { get; set; }
        public virtual DbSet<TuDienLoai> TuDienLoais { get; set; }
        public virtual DbSet<KhoGiaoDich> KhoGiaoDiches { get; set; }
        public virtual DbSet<NhomVatTu> NhomVatTus { get; set; }
        public virtual DbSet<KhoSanPham> KhoSanPhams { get; set; }
    }
}
