//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuDien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuDien()
        {
            this.KhoSanPhams = new HashSet<KhoSanPham>();
            this.KhoGiaoDiches = new HashSet<KhoGiaoDich>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid IdLoaiTuDien { get; set; }
        public string MaTuDien { get; set; }
        public string TenTuDien { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoSanPham> KhoSanPhams { get; set; }
        public virtual TuDienLoai TuDienLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoGiaoDich> KhoGiaoDiches { get; set; }
    }
}
